name: Pipeline CI CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: Lint code
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Run unit tests for preprocessing
        run: |
          pytest tests/Test_Unit_DataPreprocessing.py --maxfail=1 --disable-warnings -q

      - name: Run unit tests for model training
        run: |
          pytest tests/Test_Unit_ModelTraining.py --maxfail=1 --disable-warnings -q

  train_model:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Train the model
        run: python train_model.py

  deploy_model:
    runs-on: ubuntu-latest
    needs: [train_model]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy model
        run: |
          docker build -t my_model_image .
          docker run -d -p 5000:5000 my_model_image
