name: Pipeline CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install flake8 and black
        run: pip install flake8 black
      - name: Lint code with flake8
        run: flake8 .
      - name: Format code with black
        run: black --check .
  test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q
  train_model:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Train the model
        working-directory: .projet_ingenieurie/
        run: python train_model.py
  deploy_model:
    runs-on: ubuntu-latest
    needs: [train_model]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy model
        run: |
          docker build -t my_model_image .
          docker run -d -p 5000:5000 my_model_image

