name: CI Pipeline

on:
  push:
    branches:
      - main  # ou la branche sur laquelle tu veux déclencher la pipeline
  pull_request:
    branches:
      - main  # ou la branche sur laquelle tu veux déclencher la pipeline

jobs:
  # Job pour le linting, le formatage et l'exécution des tests
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # ou la version de Python de ton choix

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt  # Indiquer le chemin correct vers le fichier requirements.txt

      - name: Run flake8 (linting)
        run: |
          pip install flake8
          flake8 .

      - name: Run black (formatting)
        run: |
          pip install black
          black --check .  # Utilise --check pour vérifier sans effectuer de modifications

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q  # Exécute les tests et arrête après le premier échec
