name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install pytest pytest-mock  # Installe pytest et pytest-mock

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src  # Ajoute src/ au PYTHONPATH
        run: pytest tests/ --maxfail=1 --disable-warnings -q