name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Run flake8
        run: |
          pip install flake8
          flake8 --max-line-length=79 .

      - name: Run black (check formatting)
        run: |
          pip install black
          black --check --diff .  # Vérifie si le format est respecté sans appliquer les changements

  test:
    runs-on: ubuntu-latest
    needs: lint  # Cette étape dépend de l'étape de linting

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Run pytest
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q
